## Task 12

- Create arrays with all the data types available in numpy

#### Data Types
- Integer - i
- Boolean - b
- Unsigned integer - u
- Float - f
- Complex float - c
- Timedelta - m
- Datatime - M
- Object - O
- String - S
- Unicode string - U

In [1]:
import numpy as np

In [2]:
a = np.array([11,12,13,14,15])   #integer
print(a)
a.dtype

[11 12 13 14 15]


dtype('int32')

In [3]:
a = np.array([11,12,13,14,15] ,dtype= 'bool')  #boolean
print(a)
a.dtype

[ True  True  True  True  True]


dtype('bool')

In [4]:
a = np.array([-11,-12,13,14,15] ,dtype= 'uint16') #unsigned integer 
print(a)
a.dtype

[65525 65524    13    14    15]


dtype('uint16')

In [5]:
a= np.array([12,442,33.33,7.8,9.67])   #float
print(a)
a.dtype

[ 12.   442.    33.33   7.8    9.67]


dtype('float64')

In [6]:
a = np.array([10.4,1 + 12j,90.38j])  #complex float
print(a)
a.dtype

[10.4 +0.j    1. +12.j    0. +90.38j]


dtype('complex128')

In [7]:
a=np.timedelta64(5, 'Y')   #timedelta
print(a)

5 years


In [8]:
a=np.timedelta64(5, 'M')   #timedelta
print(a)

5 months


In [9]:
a=np.array(['2021-06-21', '2006-01-15', '2001-10-05'], dtype='datetime64')   #datetime
a

array(['2021-06-21', '2006-01-15', '2001-10-05'], dtype='datetime64[D]')

In [10]:
a = np.array([55,45,35], dtype='O')  #object
a

array([55, 45, 35], dtype=object)

In [11]:
a = np.array(['Harsha', 'APSSDC', 'Internship'])  #String
print(a)
a.dtype

['Harsha' 'APSSDC' 'Internship']


dtype('<U10')

In [12]:
a = np.array([u'\u0065',u'\u2202r',u'\u1F601'], dtype='U')  #unicode string
a

array(['e', '∂r', 'ὠ1'], dtype='<U2')